[package]
name = "komple-framework-types"
version = "1.0.1-beta"
authors = ["findolor <findolor@komple.io>"]
edition = "2018"
description = "Package used for type definitions in Komple Framework."
repository = "https://github.com/KompleTeam/komple-framework/tree/main/packages/types"
homepage = "https://komple.io"
license = "Apache-2.0"

[dependencies]
cosmwasm-std = "1.1.0"
cosmwasm-schema = "1.1.0"