[workspace]
members = [
    "contracts/modules/*",
    "contracts/permissions/*",
    "packages/*"
]

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false