[package]
name = "rift-utils"
version = "0.1.0"
authors = ["AnalogGhost <analoghost@proton.me>"]
edition = "2018"

[dependencies]
cosmwasm-std = { version = "1.0.0" }
rift-types = { path = "../types" }
thiserror = "1.0.30"
cw721 = "0.13.2"
schemars = "0.8.8"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
cw-storage-plus = "0.13.2"