[package]
name = "komple-framework-utils"
version = "1.0.1-beta"
authors = ["findolor <findolor@komple.io>"]
edition = "2018"
description = "Package used for utility methods in Komple Framework."
repository = "https://github.com/KompleTeam/komple-framework/tree/main/packages/utils"
homepage = "https://komple.io"
license = "Apache-2.0"

[features]
default = [
    "response",
    "funds",
    "storage"
]
response = []
funds = []
storage = [
    "dep:komple-framework-types",
    "dep:cw721-base",
    "dep:schemars",
    "dep:serde",
    "dep:cw-storage-plus",
]

[dependencies]
cosmwasm-std = { version = "1.1.0" }
komple-framework-types = { path = "../types", version = "1.0.1-beta", optional = true }
thiserror = "1.0.30"
cw721-base = { version = "0.15.0", features = ["library"], optional = true }
schemars = { version = "0.8.8", optional = true }
serde = { version = "1.0.137", default-features = false, features = ["derive"], optional = true }
cw-storage-plus = { version = "0.15.1", optional = true }
cw20 = "0.16.0"