[package]
name = "komple-utils"
version = "0.0.1"
authors = ["findolor <16416963+findolor@users.noreply.github.com>"]
edition = "2018"

[dependencies]
cosmwasm-std = { version = "1.1.0" }
komple-types = { path = "../types" }
thiserror = "1.0.30"
cw721-base = { version = "0.15.0", features = ["library"] }
schemars = "0.8.8"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
cw-storage-plus = "0.15.1"